import React, { useEffect, useRef } from 'react';
import { X, Download, ShieldCheck, Printer, CheckCircle2, AlertCircle } from 'lucide-react';
import { MedicalRecord } from '../../types';
import { PrimaryButton } from './PrimaryButton';
import { SecondaryButton } from './SecondaryButton';

interface RecordViewerModalProps {
  record: MedicalRecord | null;
  isOpen: boolean;
  onClose: () => void;
  isDoctorView?: boolean;
}

export const RecordViewerModal: React.FC<RecordViewerModalProps> = ({
  record,
  isOpen,
  onClose,
  isDoctorView = false
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Draw realistic ECG waveform on canvas when viewing ECG
  useEffect(() => {
    if (!isOpen || !record || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const width = canvas.width;
    const height = canvas.height;

    // Draw ECG Grid (Classic medical pink/salmon grid)
    ctx.fillStyle = '#FFF8F8';
    ctx.fillRect(0, 0, width, height);

    ctx.lineWidth = 0.5;
    ctx.strokeStyle = '#FCA5A5'; // minor grid
    const step = 10;
    for (let x = 0; x < width; x += step) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y < height; y += step) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    // Major grid lines
    ctx.lineWidth = 1;
    ctx.strokeStyle = '#F87171';
    for (let x = 0; x < width; x += step * 5) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y < height; y += step * 5) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    // Draw ECG waveform (P-Q-R-S-T wave)
    ctx.strokeStyle = '#0F172A';
    ctx.lineWidth = 2;
    ctx.lineJoin = 'round';
    ctx.beginPath();

    const baseline = height / 2;
    let x = 0;
    ctx.moveTo(x, baseline);

    const drawEcgBeat = () => {
      // Isoelectric
      x += 20;
      ctx.lineTo(x, baseline);
      // P wave
      x += 10;
      ctx.quadraticCurveTo(x + 5, baseline - 14, x + 10, baseline);
      x += 10;
      // PR segment
      x += 12;
      ctx.lineTo(x, baseline);
      // Q drop
      x += 4;
      ctx.lineTo(x, baseline + 8);
      // R spike
      x += 6;
      ctx.lineTo(x, baseline - 55);
      // S drop
      x += 6;
      ctx.lineTo(x, baseline + 18);
      // S return to baseline
      x += 4;
      ctx.lineTo(x, baseline);
      // ST segment
      x += 14;
      ctx.lineTo(x, baseline);
      // T wave
      x += 12;
      ctx.quadraticCurveTo(x + 10, baseline - 22, x + 20, baseline);
      x += 20;
      // Isoelectric tail
      x += 20;
      ctx.lineTo(x, baseline);
    };

    while (x < width) {
      drawEcgBeat();
    }
    ctx.stroke();

    // Add Lead II label watermark
    ctx.fillStyle = '#DC2626';
    ctx.font = 'bold 12px sans-serif';
    ctx.fillText('LEAD II (25mm/s, 10mm/mV)', 15, 20);
  }, [isOpen, record]);

  if (!isOpen || !record) return null;

  const handleDownload = () => {
    // Generate clean medical report text format
    const content = `
=================================================================
CONSULTREADY - CLINICAL MEDICAL RECORD PREVIEW
=================================================================
DOCUMENT: ${record.title.toUpperCase()}
DATE OF RECORD: ${record.date}
CATEGORY: ${record.type}
HEALTHCARE FACILITY: ${record.provider}

PATIENT INFORMATION:
Name: Ananya Sharma
Age: 29 | Gender: Female
Blood Group: B+
Identifier: PAT_994821

CLINICAL SUMMARY:
${record.clinicalSummary || 'Normal diagnostic review recorded.'}

DETAILED FINDINGS & CLINICAL OBSERVATIONS:
${record.details?.findings?.map((f, i) => `${i + 1}. ${f}`).join('\n') || 'All parameters evaluated according to standard protocol.'}

${
  record.details?.metrics
    ? `VITAL METRICS:\n` +
      record.details.metrics.map((m) => ` - ${m.label}: ${m.value} [${m.status || 'normal'}]`).join('\n')
    : ''
}

${
  record.details?.medications
    ? `MEDICATIONS:\n` +
      record.details.medications
        .map((m) => ` - ${m.name} (${m.dosage}) | Frequency: ${m.frequency} | Duration: ${m.duration}`)
        .join('\n')
    : ''
}

=================================================================
SECURITY AUDIT TRAIL:
Authorized Access: View-Only Temporary Session
Confidentiality Notice: Intended strictly for authorized clinical review.
Generated by ConsultReady Secure Health Engine.
=================================================================
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${record.title.replace(/\s+/g, '_')}_${record.date.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const isEcg = record.title.toLowerCase().includes('ecg');

  return (
    <div
      role="dialog"
      aria-modal="true"
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl max-h-[92vh] flex flex-col rounded-3xl border border-slate-200 bg-white shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4 bg-slate-50/90">
          <div className="flex items-center gap-2.5 min-w-0">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700 border border-blue-200/60 shadow-2xs">
              <ShieldCheck className="h-3.5 w-3.5 text-blue-600" />
              <span>View-only access</span>
            </span>
            <span className="text-xs text-slate-300">•</span>
            <span className="truncate text-xs font-semibold text-slate-600">
              {record.provider}
            </span>
          </div>

          <button
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-xl text-slate-400 hover:bg-slate-200/80 hover:text-slate-700 transition"
            aria-label="Close document modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Modal Scrollable Content (Simulating Clinical Document) */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-7 space-y-6">
          {/* Document Header */}
          <div className="border-b border-slate-100 pb-5">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <span className="text-[11px] font-bold uppercase tracking-wider text-blue-600">
                  {record.provider}
                </span>
                <h2 className="text-xl sm:text-2xl font-black tracking-tight text-slate-900 mt-0.5">
                  {record.title.toUpperCase()}
                </h2>
              </div>
              <div className="text-left sm:text-right">
                <span className="inline-block rounded-xl bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-700 border border-slate-200/70 shadow-2xs">
                  Date: {record.date}
                </span>
              </div>
            </div>

            {/* Patient Demographic Strip */}
            <div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-3 rounded-2xl bg-slate-50/90 p-4 border border-slate-200/80 text-xs shadow-2xs">
              <div>
                <span className="text-slate-400 block font-bold text-[10px] uppercase tracking-wider">Patient Name</span>
                <span className="font-black text-slate-900 text-sm mt-0.5 block">Ananya Sharma</span>
              </div>
              <div>
                <span className="text-slate-400 block font-bold text-[10px] uppercase tracking-wider">Age / Gender</span>
                <span className="font-bold text-slate-800 text-sm mt-0.5 block">29 / Female</span>
              </div>
              <div>
                <span className="text-slate-400 block font-bold text-[10px] uppercase tracking-wider">Patient ID</span>
                <span className="font-bold text-slate-800 font-mono text-sm mt-0.5 block">PAT_994821</span>
              </div>
              <div>
                <span className="text-slate-400 block font-bold text-[10px] uppercase tracking-wider">Ordering Doctor</span>
                <span className="font-bold text-slate-800 text-sm mt-0.5 block">Dr. V. Ramanathan</span>
              </div>
            </div>
          </div>

          {/* ECG Graphic Waveform if applicable */}
          {isEcg && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                  Lead II Rhythm Tracing (Calibration 25mm/sec)
                </h4>
                <span className="text-[11px] font-semibold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded">
                  72 BPM Regular
                </span>
              </div>

              <div className="overflow-x-auto rounded-xl border border-rose-200 shadow-inner bg-rose-50/20 p-1">
                <canvas
                  ref={canvasRef}
                  width={560}
                  height={130}
                  className="w-full h-32 rounded-lg"
                />
              </div>
            </div>
          )}

          {/* Clinical Metrics / Key Readings */}
          {record.details?.metrics && record.details.metrics.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                Quantitative Readings
              </h4>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                {record.details.metrics.map((metric, idx) => (
                    <div
                    key={idx}
                    className="rounded-2xl border border-slate-200/90 bg-white p-3.5 shadow-2xs"
                  >
                    <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
                      {metric.label}
                    </span>
                    <span className="text-base font-black text-slate-900 block mt-1">
                      {metric.value}
                    </span>
                    <span
                      className={`mt-1.5 inline-flex items-center gap-1 text-[10px] font-bold ${
                        metric.status === 'warning'
                          ? 'text-amber-600'
                          : metric.status === 'critical'
                          ? 'text-rose-600'
                          : 'text-emerald-600'
                      }`}
                    >
                      {metric.status === 'warning' ? (
                        <AlertCircle className="h-3 w-3" />
                      ) : (
                        <CheckCircle2 className="h-3 w-3" />
                      )}
                      <span>
                        {metric.status === 'warning'
                          ? 'Borderline'
                          : metric.status === 'critical'
                          ? 'Critical'
                          : 'Normal Range'}
                      </span>
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Medications list if applicable */}
          {record.details?.medications && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
                Prescribed Drug Regimen
              </h4>
              <div className="divide-y divide-slate-100 rounded-2xl border border-slate-200/90 bg-white overflow-hidden shadow-2xs">
                {record.details.medications.map((med, idx) => (
                  <div key={idx} className="p-3.5 text-xs flex items-center justify-between gap-3">
                    <div>
                      <span className="font-black text-slate-900 text-sm">{med.name}</span>
                      <span className="ml-2 font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-200/50">{med.dosage}</span>
                      <p className="text-slate-500 mt-1 font-medium">{med.frequency}</p>
                    </div>
                    <span className="rounded-xl bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-700">
                      {med.duration}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Clinical Findings & Summary */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
              Clinical Impression & Findings
            </h4>
            <div className="rounded-2xl border border-slate-200/90 bg-slate-50/70 p-4 sm:p-5 space-y-2 text-xs text-slate-700 leading-relaxed shadow-2xs">
              <p className="font-bold text-slate-900 text-sm">
                {record.clinicalSummary || 'Standard clinical review.'}
              </p>
              {record.details?.findings && (
                <ul className="list-disc pl-4 space-y-1.5 text-slate-600 pt-1">
                  {record.details.findings.map((finding, idx) => (
                    <li key={idx} className="font-medium">{finding}</li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="border-t border-slate-100 bg-slate-50/90 px-6 py-4 flex items-center justify-between gap-3">
          <span className="text-xs font-medium text-slate-500 hidden sm:inline">
            Electronic Medical Record Preview • Encrypted
          </span>
          <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
            <SecondaryButton onClick={onClose} size="sm">
              Close
            </SecondaryButton>
            <PrimaryButton
              onClick={handleDownload}
              size="sm"
              icon={<Download className="h-4 w-4" />}
            >
              Download Report
            </PrimaryButton>
          </div>
        </div>
      </div>
    </div>
  );
};
